name: "Roblox"

on:
  push:
    paths:
      - "wally.toml"
  workflow_dispatch:

jobs:
  workflow:
    uses: Bloxfront/.github/.github/workflows/roblox.yml@main

    secrets: inherit
    permissions:
        contents: write